// AUTO-GENERATED by the Block A image optimization pass. Do not edit by hand.
// Derived AVIF/WebP variants of the original static PNG assets (originals kept untouched).

import v_bagnone_lunigiana_640_avif from "@/assets/opt/bagnone-lunigiana-640.avif.asset.json";
import v_bagnone_lunigiana_1024_avif from "@/assets/opt/bagnone-lunigiana-1024.avif.asset.json";
import v_bagnone_lunigiana_1446_avif from "@/assets/opt/bagnone-lunigiana-1446.avif.asset.json";
import v_bagnone_lunigiana_640_webp from "@/assets/opt/bagnone-lunigiana-640.webp.asset.json";
import v_bagnone_lunigiana_1024_webp from "@/assets/opt/bagnone-lunigiana-1024.webp.asset.json";
import v_bagnone_lunigiana_1446_webp from "@/assets/opt/bagnone-lunigiana-1446.webp.asset.json";
import v_elena_furia_640_avif from "@/assets/opt/elena-furia-640.avif.asset.json";
import v_elena_furia_1024_avif from "@/assets/opt/elena-furia-1024.avif.asset.json";
import v_elena_furia_1086_avif from "@/assets/opt/elena-furia-1086.avif.asset.json";
import v_elena_furia_640_webp from "@/assets/opt/elena-furia-640.webp.asset.json";
import v_elena_furia_1024_webp from "@/assets/opt/elena-furia-1024.webp.asset.json";
import v_elena_furia_1086_webp from "@/assets/opt/elena-furia-1086.webp.asset.json";
import v_filattiera_lunigiana_640_avif from "@/assets/opt/filattiera-lunigiana-640.avif.asset.json";
import v_filattiera_lunigiana_1024_avif from "@/assets/opt/filattiera-lunigiana-1024.avif.asset.json";
import v_filattiera_lunigiana_1600_avif from "@/assets/opt/filattiera-lunigiana-1600.avif.asset.json";
import v_filattiera_lunigiana_640_webp from "@/assets/opt/filattiera-lunigiana-640.webp.asset.json";
import v_filattiera_lunigiana_1024_webp from "@/assets/opt/filattiera-lunigiana-1024.webp.asset.json";
import v_filattiera_lunigiana_1600_webp from "@/assets/opt/filattiera-lunigiana-1600.webp.asset.json";
import v_furia_logo_240_avif from "@/assets/opt/furia-logo-240.avif.asset.json";
import v_furia_logo_480_avif from "@/assets/opt/furia-logo-480.avif.asset.json";
import v_furia_logo_240_webp from "@/assets/opt/furia-logo-240.webp.asset.json";
import v_furia_logo_480_webp from "@/assets/opt/furia-logo-480.webp.asset.json";
import v_furia_watermark_240_avif from "@/assets/opt/furia-watermark-240.avif.asset.json";
import v_furia_watermark_480_avif from "@/assets/opt/furia-watermark-480.avif.asset.json";
import v_furia_watermark_240_webp from "@/assets/opt/furia-watermark-240.webp.asset.json";
import v_furia_watermark_480_webp from "@/assets/opt/furia-watermark-480.webp.asset.json";
import v_hero_tramonto_ulivi_640_avif from "@/assets/opt/hero-tramonto-ulivi-640.avif.asset.json";
import v_hero_tramonto_ulivi_1024_avif from "@/assets/opt/hero-tramonto-ulivi-1024.avif.asset.json";
import v_hero_tramonto_ulivi_1537_avif from "@/assets/opt/hero-tramonto-ulivi-1537.avif.asset.json";
import v_hero_tramonto_ulivi_640_webp from "@/assets/opt/hero-tramonto-ulivi-640.webp.asset.json";
import v_hero_tramonto_ulivi_1024_webp from "@/assets/opt/hero-tramonto-ulivi-1024.webp.asset.json";
import v_hero_tramonto_ulivi_1537_webp from "@/assets/opt/hero-tramonto-ulivi-1537.webp.asset.json";
import v_lunigiana_hero_tramonto_640_avif from "@/assets/opt/lunigiana-hero-tramonto-640.avif.asset.json";
import v_lunigiana_hero_tramonto_1024_avif from "@/assets/opt/lunigiana-hero-tramonto-1024.avif.asset.json";
import v_lunigiana_hero_tramonto_1448_avif from "@/assets/opt/lunigiana-hero-tramonto-1448.avif.asset.json";
import v_lunigiana_hero_tramonto_640_webp from "@/assets/opt/lunigiana-hero-tramonto-640.webp.asset.json";
import v_lunigiana_hero_tramonto_1024_webp from "@/assets/opt/lunigiana-hero-tramonto-1024.webp.asset.json";
import v_lunigiana_hero_tramonto_1448_webp from "@/assets/opt/lunigiana-hero-tramonto-1448.webp.asset.json";
import v_mulazzo_lunigiana_640_avif from "@/assets/opt/mulazzo-lunigiana-640.avif.asset.json";
import v_mulazzo_lunigiana_1024_avif from "@/assets/opt/mulazzo-lunigiana-1024.avif.asset.json";
import v_mulazzo_lunigiana_1448_avif from "@/assets/opt/mulazzo-lunigiana-1448.avif.asset.json";
import v_mulazzo_lunigiana_640_webp from "@/assets/opt/mulazzo-lunigiana-640.webp.asset.json";
import v_mulazzo_lunigiana_1024_webp from "@/assets/opt/mulazzo-lunigiana-1024.webp.asset.json";
import v_mulazzo_lunigiana_1448_webp from "@/assets/opt/mulazzo-lunigiana-1448.webp.asset.json";
import v_pontremoli_hero_centro_storico_640_avif from "@/assets/opt/pontremoli-hero-centro-storico-640.avif.asset.json";
import v_pontremoli_hero_centro_storico_1024_avif from "@/assets/opt/pontremoli-hero-centro-storico-1024.avif.asset.json";
import v_pontremoli_hero_centro_storico_1578_avif from "@/assets/opt/pontremoli-hero-centro-storico-1578.avif.asset.json";
import v_pontremoli_hero_centro_storico_640_webp from "@/assets/opt/pontremoli-hero-centro-storico-640.webp.asset.json";
import v_pontremoli_hero_centro_storico_1024_webp from "@/assets/opt/pontremoli-hero-centro-storico-1024.webp.asset.json";
import v_pontremoli_hero_centro_storico_1578_webp from "@/assets/opt/pontremoli-hero-centro-storico-1578.webp.asset.json";
import v_pontremoli_lunigiana_v2_640_avif from "@/assets/opt/pontremoli-lunigiana-v2-640.avif.asset.json";
import v_pontremoli_lunigiana_v2_1024_avif from "@/assets/opt/pontremoli-lunigiana-v2-1024.avif.asset.json";
import v_pontremoli_lunigiana_v2_1600_avif from "@/assets/opt/pontremoli-lunigiana-v2-1600.avif.asset.json";
import v_pontremoli_lunigiana_v2_640_webp from "@/assets/opt/pontremoli-lunigiana-v2-640.webp.asset.json";
import v_pontremoli_lunigiana_v2_1024_webp from "@/assets/opt/pontremoli-lunigiana-v2-1024.webp.asset.json";
import v_pontremoli_lunigiana_v2_1600_webp from "@/assets/opt/pontremoli-lunigiana-v2-1600.webp.asset.json";
import v_villafranca_lunigiana_640_avif from "@/assets/opt/villafranca-lunigiana-640.avif.asset.json";
import v_villafranca_lunigiana_1024_avif from "@/assets/opt/villafranca-lunigiana-1024.avif.asset.json";
import v_villafranca_lunigiana_1600_avif from "@/assets/opt/villafranca-lunigiana-1600.avif.asset.json";
import v_villafranca_lunigiana_640_webp from "@/assets/opt/villafranca-lunigiana-640.webp.asset.json";
import v_villafranca_lunigiana_1024_webp from "@/assets/opt/villafranca-lunigiana-1024.webp.asset.json";
import v_villafranca_lunigiana_1600_webp from "@/assets/opt/villafranca-lunigiana-1600.webp.asset.json";
import v_zeri_lunigiana_640_avif from "@/assets/opt/zeri-lunigiana-640.avif.asset.json";
import v_zeri_lunigiana_1024_avif from "@/assets/opt/zeri-lunigiana-1024.avif.asset.json";
import v_zeri_lunigiana_1448_avif from "@/assets/opt/zeri-lunigiana-1448.avif.asset.json";
import v_zeri_lunigiana_640_webp from "@/assets/opt/zeri-lunigiana-640.webp.asset.json";
import v_zeri_lunigiana_1024_webp from "@/assets/opt/zeri-lunigiana-1024.webp.asset.json";
import v_zeri_lunigiana_1448_webp from "@/assets/opt/zeri-lunigiana-1448.webp.asset.json";

import type { StaticImageSet } from "./static-image-set";

export const STATIC_IMAGE_SETS: Record<string, StaticImageSet> = {
  "bagnone-lunigiana": {
    width: 1446, height: 1087,
    avif: [`${v_bagnone_lunigiana_640_avif.url} 640w`, `${v_bagnone_lunigiana_1024_avif.url} 1024w`, `${v_bagnone_lunigiana_1446_avif.url} 1446w`].join(", "),
    webp: [`${v_bagnone_lunigiana_640_webp.url} 640w`, `${v_bagnone_lunigiana_1024_webp.url} 1024w`, `${v_bagnone_lunigiana_1446_webp.url} 1446w`].join(", "),
    src: v_bagnone_lunigiana_1446_webp.url,
  },
  "elena-furia": {
    width: 1086, height: 1448,
    avif: [`${v_elena_furia_640_avif.url} 640w`, `${v_elena_furia_1024_avif.url} 1024w`, `${v_elena_furia_1086_avif.url} 1086w`].join(", "),
    webp: [`${v_elena_furia_640_webp.url} 640w`, `${v_elena_furia_1024_webp.url} 1024w`, `${v_elena_furia_1086_webp.url} 1086w`].join(", "),
    src: v_elena_furia_1086_webp.url,
  },
  "filattiera-lunigiana": {
    width: 1600, height: 812,
    avif: [`${v_filattiera_lunigiana_640_avif.url} 640w`, `${v_filattiera_lunigiana_1024_avif.url} 1024w`, `${v_filattiera_lunigiana_1600_avif.url} 1600w`].join(", "),
    webp: [`${v_filattiera_lunigiana_640_webp.url} 640w`, `${v_filattiera_lunigiana_1024_webp.url} 1024w`, `${v_filattiera_lunigiana_1600_webp.url} 1600w`].join(", "),
    src: v_filattiera_lunigiana_1600_webp.url,
  },
  "furia-logo": {
    width: 480, height: 259,
    avif: [`${v_furia_logo_240_avif.url} 240w`, `${v_furia_logo_480_avif.url} 480w`].join(", "),
    webp: [`${v_furia_logo_240_webp.url} 240w`, `${v_furia_logo_480_webp.url} 480w`].join(", "),
    src: v_furia_logo_480_webp.url,
  },
  "furia-watermark": {
    width: 480, height: 270,
    avif: [`${v_furia_watermark_240_avif.url} 240w`, `${v_furia_watermark_480_avif.url} 480w`].join(", "),
    webp: [`${v_furia_watermark_240_webp.url} 240w`, `${v_furia_watermark_480_webp.url} 480w`].join(", "),
    src: v_furia_watermark_480_webp.url,
  },
  "hero-tramonto-ulivi": {
    width: 1537, height: 1023,
    avif: [`${v_hero_tramonto_ulivi_640_avif.url} 640w`, `${v_hero_tramonto_ulivi_1024_avif.url} 1024w`, `${v_hero_tramonto_ulivi_1537_avif.url} 1537w`].join(", "),
    webp: [`${v_hero_tramonto_ulivi_640_webp.url} 640w`, `${v_hero_tramonto_ulivi_1024_webp.url} 1024w`, `${v_hero_tramonto_ulivi_1537_webp.url} 1537w`].join(", "),
    src: v_hero_tramonto_ulivi_1537_webp.url,
  },
  "lunigiana-hero-tramonto": {
    width: 1448, height: 1086,
    avif: [`${v_lunigiana_hero_tramonto_640_avif.url} 640w`, `${v_lunigiana_hero_tramonto_1024_avif.url} 1024w`, `${v_lunigiana_hero_tramonto_1448_avif.url} 1448w`].join(", "),
    webp: [`${v_lunigiana_hero_tramonto_640_webp.url} 640w`, `${v_lunigiana_hero_tramonto_1024_webp.url} 1024w`, `${v_lunigiana_hero_tramonto_1448_webp.url} 1448w`].join(", "),
    src: v_lunigiana_hero_tramonto_1448_webp.url,
  },
  "mulazzo-lunigiana": {
    width: 1448, height: 1086,
    avif: [`${v_mulazzo_lunigiana_640_avif.url} 640w`, `${v_mulazzo_lunigiana_1024_avif.url} 1024w`, `${v_mulazzo_lunigiana_1448_avif.url} 1448w`].join(", "),
    webp: [`${v_mulazzo_lunigiana_640_webp.url} 640w`, `${v_mulazzo_lunigiana_1024_webp.url} 1024w`, `${v_mulazzo_lunigiana_1448_webp.url} 1448w`].join(", "),
    src: v_mulazzo_lunigiana_1448_webp.url,
  },
  "pontremoli-hero-centro-storico": {
    width: 1578, height: 997,
    avif: [`${v_pontremoli_hero_centro_storico_640_avif.url} 640w`, `${v_pontremoli_hero_centro_storico_1024_avif.url} 1024w`, `${v_pontremoli_hero_centro_storico_1578_avif.url} 1578w`].join(", "),
    webp: [`${v_pontremoli_hero_centro_storico_640_webp.url} 640w`, `${v_pontremoli_hero_centro_storico_1024_webp.url} 1024w`, `${v_pontremoli_hero_centro_storico_1578_webp.url} 1578w`].join(", "),
    src: v_pontremoli_hero_centro_storico_1578_webp.url,
  },
  "pontremoli-lunigiana-v2": {
    width: 1600, height: 735,
    avif: [`${v_pontremoli_lunigiana_v2_640_avif.url} 640w`, `${v_pontremoli_lunigiana_v2_1024_avif.url} 1024w`, `${v_pontremoli_lunigiana_v2_1600_avif.url} 1600w`].join(", "),
    webp: [`${v_pontremoli_lunigiana_v2_640_webp.url} 640w`, `${v_pontremoli_lunigiana_v2_1024_webp.url} 1024w`, `${v_pontremoli_lunigiana_v2_1600_webp.url} 1600w`].join(", "),
    src: v_pontremoli_lunigiana_v2_1600_webp.url,
  },
  "villafranca-lunigiana": {
    width: 1600, height: 900,
    avif: [`${v_villafranca_lunigiana_640_avif.url} 640w`, `${v_villafranca_lunigiana_1024_avif.url} 1024w`, `${v_villafranca_lunigiana_1600_avif.url} 1600w`].join(", "),
    webp: [`${v_villafranca_lunigiana_640_webp.url} 640w`, `${v_villafranca_lunigiana_1024_webp.url} 1024w`, `${v_villafranca_lunigiana_1600_webp.url} 1600w`].join(", "),
    src: v_villafranca_lunigiana_1600_webp.url,
  },
  "zeri-lunigiana": {
    width: 1448, height: 1086,
    avif: [`${v_zeri_lunigiana_640_avif.url} 640w`, `${v_zeri_lunigiana_1024_avif.url} 1024w`, `${v_zeri_lunigiana_1448_avif.url} 1448w`].join(", "),
    webp: [`${v_zeri_lunigiana_640_webp.url} 640w`, `${v_zeri_lunigiana_1024_webp.url} 1024w`, `${v_zeri_lunigiana_1448_webp.url} 1448w`].join(", "),
    src: v_zeri_lunigiana_1448_webp.url,
  },
};
