/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerritoriRouteImport } from './routes/territori'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as ImmobiliRouteImport } from './routes/immobili'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImmobiliIndexRouteImport } from './routes/immobili.index'
import { Route as ImmobiliIdRouteImport } from './routes/immobili.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminRichiesteRouteImport } from './routes/_admin.admin.richieste'
import { Route as AdminAdminImpostazioniRouteImport } from './routes/_admin.admin.impostazioni'
import { Route as AdminAdminIdealistaRouteImport } from './routes/_admin.admin.idealista'
import { Route as AdminAdminImmobiliIndexRouteImport } from './routes/_admin.admin.immobili.index'
import { Route as ApiPublicIdealistaFeedDotxmlRouteImport } from './routes/api/public/idealista/feed[.]xml'
import { Route as AdminAdminImmobiliNuovoRouteImport } from './routes/_admin.admin.immobili.nuovo'
import { Route as AdminAdminImmobiliAssistenteRouteImport } from './routes/_admin.admin.immobili.assistente'
import { Route as AdminAdminImmobiliIdRouteImport } from './routes/_admin.admin.immobili.$id'
import { Route as AdminAdminImmobiliIdAnteprimaRouteImport } from './routes/_admin.admin.immobili.$id.anteprima'

const TerritoriRoute = TerritoriRouteImport.update({
  id: '/territori',
  path: '/territori',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobiliRoute = ImmobiliRouteImport.update({
  id: '/immobili',
  path: '/immobili',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobiliIndexRoute = ImmobiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImmobiliRoute,
} as any)
const ImmobiliIdRoute = ImmobiliIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ImmobiliRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRichiesteRoute = AdminAdminRichiesteRouteImport.update({
  id: '/richieste',
  path: '/richieste',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminImpostazioniRoute = AdminAdminImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminIdealistaRoute = AdminAdminIdealistaRouteImport.update({
  id: '/idealista',
  path: '/idealista',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminImmobiliIndexRoute = AdminAdminImmobiliIndexRouteImport.update({
  id: '/immobili/',
  path: '/immobili/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiPublicIdealistaFeedDotxmlRoute =
  ApiPublicIdealistaFeedDotxmlRouteImport.update({
    id: '/api/public/idealista/feed.xml',
    path: '/api/public/idealista/feed.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminImmobiliNuovoRoute = AdminAdminImmobiliNuovoRouteImport.update({
  id: '/immobili/nuovo',
  path: '/immobili/nuovo',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminImmobiliAssistenteRoute =
  AdminAdminImmobiliAssistenteRouteImport.update({
    id: '/immobili/assistente',
    path: '/immobili/assistente',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminImmobiliIdRoute = AdminAdminImmobiliIdRouteImport.update({
  id: '/immobili/$id',
  path: '/immobili/$id',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminImmobiliIdAnteprimaRoute =
  AdminAdminImmobiliIdAnteprimaRouteImport.update({
    id: '/anteprima',
    path: '/anteprima',
    getParentRoute: () => AdminAdminImmobiliIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/immobili': typeof ImmobiliRouteWithChildren
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territori': typeof TerritoriRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/immobili/$id': typeof ImmobiliIdRoute
  '/immobili/': typeof ImmobiliIndexRoute
  '/admin/idealista': typeof AdminAdminIdealistaRoute
  '/admin/impostazioni': typeof AdminAdminImpostazioniRoute
  '/admin/richieste': typeof AdminAdminRichiesteRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/immobili/$id': typeof AdminAdminImmobiliIdRouteWithChildren
  '/admin/immobili/assistente': typeof AdminAdminImmobiliAssistenteRoute
  '/admin/immobili/nuovo': typeof AdminAdminImmobiliNuovoRoute
  '/api/public/idealista/feed.xml': typeof ApiPublicIdealistaFeedDotxmlRoute
  '/admin/immobili/': typeof AdminAdminImmobiliIndexRoute
  '/admin/immobili/$id/anteprima': typeof AdminAdminImmobiliIdAnteprimaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territori': typeof TerritoriRoute
  '/admin/login': typeof AdminLoginRoute
  '/immobili/$id': typeof ImmobiliIdRoute
  '/immobili': typeof ImmobiliIndexRoute
  '/admin/idealista': typeof AdminAdminIdealistaRoute
  '/admin/impostazioni': typeof AdminAdminImpostazioniRoute
  '/admin/richieste': typeof AdminAdminRichiesteRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/immobili/$id': typeof AdminAdminImmobiliIdRouteWithChildren
  '/admin/immobili/assistente': typeof AdminAdminImmobiliAssistenteRoute
  '/admin/immobili/nuovo': typeof AdminAdminImmobiliNuovoRoute
  '/api/public/idealista/feed.xml': typeof ApiPublicIdealistaFeedDotxmlRoute
  '/admin/immobili': typeof AdminAdminImmobiliIndexRoute
  '/admin/immobili/$id/anteprima': typeof AdminAdminImmobiliIdAnteprimaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/immobili': typeof ImmobiliRouteWithChildren
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territori': typeof TerritoriRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/immobili/$id': typeof ImmobiliIdRoute
  '/immobili/': typeof ImmobiliIndexRoute
  '/_admin/admin/idealista': typeof AdminAdminIdealistaRoute
  '/_admin/admin/impostazioni': typeof AdminAdminImpostazioniRoute
  '/_admin/admin/richieste': typeof AdminAdminRichiesteRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/immobili/$id': typeof AdminAdminImmobiliIdRouteWithChildren
  '/_admin/admin/immobili/assistente': typeof AdminAdminImmobiliAssistenteRoute
  '/_admin/admin/immobili/nuovo': typeof AdminAdminImmobiliNuovoRoute
  '/api/public/idealista/feed.xml': typeof ApiPublicIdealistaFeedDotxmlRoute
  '/_admin/admin/immobili/': typeof AdminAdminImmobiliIndexRoute
  '/_admin/admin/immobili/$id/anteprima': typeof AdminAdminImmobiliIdAnteprimaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/immobili'
    | '/servizi'
    | '/sitemap.xml'
    | '/territori'
    | '/admin'
    | '/admin/login'
    | '/immobili/$id'
    | '/immobili/'
    | '/admin/idealista'
    | '/admin/impostazioni'
    | '/admin/richieste'
    | '/admin/'
    | '/admin/immobili/$id'
    | '/admin/immobili/assistente'
    | '/admin/immobili/nuovo'
    | '/api/public/idealista/feed.xml'
    | '/admin/immobili/'
    | '/admin/immobili/$id/anteprima'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/servizi'
    | '/sitemap.xml'
    | '/territori'
    | '/admin/login'
    | '/immobili/$id'
    | '/immobili'
    | '/admin/idealista'
    | '/admin/impostazioni'
    | '/admin/richieste'
    | '/admin'
    | '/admin/immobili/$id'
    | '/admin/immobili/assistente'
    | '/admin/immobili/nuovo'
    | '/api/public/idealista/feed.xml'
    | '/admin/immobili'
    | '/admin/immobili/$id/anteprima'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/chi-siamo'
    | '/contatti'
    | '/immobili'
    | '/servizi'
    | '/sitemap.xml'
    | '/territori'
    | '/_admin/admin'
    | '/admin/login'
    | '/immobili/$id'
    | '/immobili/'
    | '/_admin/admin/idealista'
    | '/_admin/admin/impostazioni'
    | '/_admin/admin/richieste'
    | '/_admin/admin/'
    | '/_admin/admin/immobili/$id'
    | '/_admin/admin/immobili/assistente'
    | '/_admin/admin/immobili/nuovo'
    | '/api/public/idealista/feed.xml'
    | '/_admin/admin/immobili/'
    | '/_admin/admin/immobili/$id/anteprima'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  ImmobiliRoute: typeof ImmobiliRouteWithChildren
  ServiziRoute: typeof ServiziRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerritoriRoute: typeof TerritoriRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicIdealistaFeedDotxmlRoute: typeof ApiPublicIdealistaFeedDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/territori': {
      id: '/territori'
      path: '/territori'
      fullPath: '/territori'
      preLoaderRoute: typeof TerritoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobili': {
      id: '/immobili'
      path: '/immobili'
      fullPath: '/immobili'
      preLoaderRoute: typeof ImmobiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobili/': {
      id: '/immobili/'
      path: '/'
      fullPath: '/immobili/'
      preLoaderRoute: typeof ImmobiliIndexRouteImport
      parentRoute: typeof ImmobiliRoute
    }
    '/immobili/$id': {
      id: '/immobili/$id'
      path: '/$id'
      fullPath: '/immobili/$id'
      preLoaderRoute: typeof ImmobiliIdRouteImport
      parentRoute: typeof ImmobiliRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/richieste': {
      id: '/_admin/admin/richieste'
      path: '/richieste'
      fullPath: '/admin/richieste'
      preLoaderRoute: typeof AdminAdminRichiesteRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/impostazioni': {
      id: '/_admin/admin/impostazioni'
      path: '/impostazioni'
      fullPath: '/admin/impostazioni'
      preLoaderRoute: typeof AdminAdminImpostazioniRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/idealista': {
      id: '/_admin/admin/idealista'
      path: '/idealista'
      fullPath: '/admin/idealista'
      preLoaderRoute: typeof AdminAdminIdealistaRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/immobili/': {
      id: '/_admin/admin/immobili/'
      path: '/immobili'
      fullPath: '/admin/immobili/'
      preLoaderRoute: typeof AdminAdminImmobiliIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/public/idealista/feed.xml': {
      id: '/api/public/idealista/feed.xml'
      path: '/api/public/idealista/feed.xml'
      fullPath: '/api/public/idealista/feed.xml'
      preLoaderRoute: typeof ApiPublicIdealistaFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/immobili/nuovo': {
      id: '/_admin/admin/immobili/nuovo'
      path: '/immobili/nuovo'
      fullPath: '/admin/immobili/nuovo'
      preLoaderRoute: typeof AdminAdminImmobiliNuovoRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/immobili/assistente': {
      id: '/_admin/admin/immobili/assistente'
      path: '/immobili/assistente'
      fullPath: '/admin/immobili/assistente'
      preLoaderRoute: typeof AdminAdminImmobiliAssistenteRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/immobili/$id': {
      id: '/_admin/admin/immobili/$id'
      path: '/immobili/$id'
      fullPath: '/admin/immobili/$id'
      preLoaderRoute: typeof AdminAdminImmobiliIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/immobili/$id/anteprima': {
      id: '/_admin/admin/immobili/$id/anteprima'
      path: '/anteprima'
      fullPath: '/admin/immobili/$id/anteprima'
      preLoaderRoute: typeof AdminAdminImmobiliIdAnteprimaRouteImport
      parentRoute: typeof AdminAdminImmobiliIdRoute
    }
  }
}

interface AdminAdminImmobiliIdRouteChildren {
  AdminAdminImmobiliIdAnteprimaRoute: typeof AdminAdminImmobiliIdAnteprimaRoute
}

const AdminAdminImmobiliIdRouteChildren: AdminAdminImmobiliIdRouteChildren = {
  AdminAdminImmobiliIdAnteprimaRoute: AdminAdminImmobiliIdAnteprimaRoute,
}

const AdminAdminImmobiliIdRouteWithChildren =
  AdminAdminImmobiliIdRoute._addFileChildren(AdminAdminImmobiliIdRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminIdealistaRoute: typeof AdminAdminIdealistaRoute
  AdminAdminImpostazioniRoute: typeof AdminAdminImpostazioniRoute
  AdminAdminRichiesteRoute: typeof AdminAdminRichiesteRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminImmobiliIdRoute: typeof AdminAdminImmobiliIdRouteWithChildren
  AdminAdminImmobiliAssistenteRoute: typeof AdminAdminImmobiliAssistenteRoute
  AdminAdminImmobiliNuovoRoute: typeof AdminAdminImmobiliNuovoRoute
  AdminAdminImmobiliIndexRoute: typeof AdminAdminImmobiliIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminIdealistaRoute: AdminAdminIdealistaRoute,
  AdminAdminImpostazioniRoute: AdminAdminImpostazioniRoute,
  AdminAdminRichiesteRoute: AdminAdminRichiesteRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminImmobiliIdRoute: AdminAdminImmobiliIdRouteWithChildren,
  AdminAdminImmobiliAssistenteRoute: AdminAdminImmobiliAssistenteRoute,
  AdminAdminImmobiliNuovoRoute: AdminAdminImmobiliNuovoRoute,
  AdminAdminImmobiliIndexRoute: AdminAdminImmobiliIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ImmobiliRouteChildren {
  ImmobiliIdRoute: typeof ImmobiliIdRoute
  ImmobiliIndexRoute: typeof ImmobiliIndexRoute
}

const ImmobiliRouteChildren: ImmobiliRouteChildren = {
  ImmobiliIdRoute: ImmobiliIdRoute,
  ImmobiliIndexRoute: ImmobiliIndexRoute,
}

const ImmobiliRouteWithChildren = ImmobiliRoute._addFileChildren(
  ImmobiliRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  ImmobiliRoute: ImmobiliRouteWithChildren,
  ServiziRoute: ServiziRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerritoriRoute: TerritoriRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicIdealistaFeedDotxmlRoute: ApiPublicIdealistaFeedDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
