export const PROPERTY_TYPES = [
  "Casale",
  "Rustico",
  "Villa",
  "Casa indipendente",
  "Terratetto",
  "Appartamento",
  "Attico",
  "Bifamiliare",
  "Semindipendente",
  "Podere",
  "Agriturismo",
  "Borgo / proprietà storica",
  "Terreno agricolo",
  "Terreno edificabile",
  "Locale commerciale",
  "Altro",
] as const;

export const CONTRACT_TYPES = ["Vendita", "Affitto"] as const;

export const ENERGY_CLASSES = [
  "A4",
  "A3",
  "A2",
  "A1",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "In fase di definizione",
  "Esente",
] as const;

export const CONDITIONS = [
  "Nuovo",
  "Ristrutturato",
  "Ottimo",
  "Buono",
  "Abitabile",
  "Da ristrutturare",
  "Grezzo",
] as const;

export const FURNISHED_OPTIONS = ["Sì", "No", "Parzialmente"] as const;
export type FurnishedOption = (typeof FURNISHED_OPTIONS)[number];

export const HEATING_OPTIONS = [
  "Autonomo",
  "Centralizzato",
  "Assente",
  "Pompa di calore",
  "Altro",
] as const;

export const FLOOR_OPTIONS = [
  "Seminterrato",
  "Terra",
  "Rialzato",
  "1",
  "2",
  "3",
  "4",
  "5+",
  "Ultimo piano",
] as const;

/** Mappa il label piano al valore numerico salvato in `properties.floors`.
 * `null` significa: non salvare un intero (solo il label resta nei features). */
export const FLOOR_TO_NUMBER: Record<string, number | null> = {
  Seminterrato: -1,
  Terra: 0,
  Rialzato: 0,
  "1": 1,
  "2": 2,
  "3": 3,
  "4": 4,
  "5+": 5,
  "Ultimo piano": null,
};

export const REGIONS = [
  "Abruzzo",
  "Basilicata",
  "Calabria",
  "Campania",
  "Emilia-Romagna",
  "Friuli-Venezia Giulia",
  "Lazio",
  "Liguria",
  "Lombardia",
  "Marche",
  "Molise",
  "Piemonte",
  "Puglia",
  "Sardegna",
  "Sicilia",
  "Toscana",
  "Trentino-Alto Adige",
  "Umbria",
  "Valle d'Aosta",
  "Veneto",
] as const;

/** Province italiane (sigla — nome). Ordinate alfabeticamente per nome. */
export const PROVINCES: Array<{ code: string; name: string }> = [
  { code: "AG", name: "Agrigento" },
  { code: "AL", name: "Alessandria" },
  { code: "AN", name: "Ancona" },
  { code: "AO", name: "Aosta" },
  { code: "AR", name: "Arezzo" },
  { code: "AP", name: "Ascoli Piceno" },
  { code: "AT", name: "Asti" },
  { code: "AV", name: "Avellino" },
  { code: "BA", name: "Bari" },
  { code: "BT", name: "Barletta-Andria-Trani" },
  { code: "BL", name: "Belluno" },
  { code: "BN", name: "Benevento" },
  { code: "BG", name: "Bergamo" },
  { code: "BI", name: "Biella" },
  { code: "BO", name: "Bologna" },
  { code: "BZ", name: "Bolzano" },
  { code: "BS", name: "Brescia" },
  { code: "BR", name: "Brindisi" },
  { code: "CA", name: "Cagliari" },
  { code: "CL", name: "Caltanissetta" },
  { code: "CB", name: "Campobasso" },
  { code: "CE", name: "Caserta" },
  { code: "CT", name: "Catania" },
  { code: "CZ", name: "Catanzaro" },
  { code: "CH", name: "Chieti" },
  { code: "CO", name: "Como" },
  { code: "CS", name: "Cosenza" },
  { code: "CR", name: "Cremona" },
  { code: "KR", name: "Crotone" },
  { code: "CN", name: "Cuneo" },
  { code: "EN", name: "Enna" },
  { code: "FM", name: "Fermo" },
  { code: "FE", name: "Ferrara" },
  { code: "FI", name: "Firenze" },
  { code: "FG", name: "Foggia" },
  { code: "FC", name: "Forlì-Cesena" },
  { code: "FR", name: "Frosinone" },
  { code: "GE", name: "Genova" },
  { code: "GO", name: "Gorizia" },
  { code: "GR", name: "Grosseto" },
  { code: "IM", name: "Imperia" },
  { code: "IS", name: "Isernia" },
  { code: "SP", name: "La Spezia" },
  { code: "AQ", name: "L'Aquila" },
  { code: "LT", name: "Latina" },
  { code: "LE", name: "Lecce" },
  { code: "LC", name: "Lecco" },
  { code: "LI", name: "Livorno" },
  { code: "LO", name: "Lodi" },
  { code: "LU", name: "Lucca" },
  { code: "MC", name: "Macerata" },
  { code: "MN", name: "Mantova" },
  { code: "MS", name: "Massa-Carrara" },
  { code: "MT", name: "Matera" },
  { code: "ME", name: "Messina" },
  { code: "MI", name: "Milano" },
  { code: "MO", name: "Modena" },
  { code: "MB", name: "Monza e della Brianza" },
  { code: "NA", name: "Napoli" },
  { code: "NO", name: "Novara" },
  { code: "NU", name: "Nuoro" },
  { code: "OR", name: "Oristano" },
  { code: "PD", name: "Padova" },
  { code: "PA", name: "Palermo" },
  { code: "PR", name: "Parma" },
  { code: "PV", name: "Pavia" },
  { code: "PG", name: "Perugia" },
  { code: "PU", name: "Pesaro e Urbino" },
  { code: "PE", name: "Pescara" },
  { code: "PC", name: "Piacenza" },
  { code: "PI", name: "Pisa" },
  { code: "PT", name: "Pistoia" },
  { code: "PN", name: "Pordenone" },
  { code: "PZ", name: "Potenza" },
  { code: "PO", name: "Prato" },
  { code: "RG", name: "Ragusa" },
  { code: "RA", name: "Ravenna" },
  { code: "RC", name: "Reggio Calabria" },
  { code: "RE", name: "Reggio Emilia" },
  { code: "RI", name: "Rieti" },
  { code: "RN", name: "Rimini" },
  { code: "RM", name: "Roma" },
  { code: "RO", name: "Rovigo" },
  { code: "SA", name: "Salerno" },
  { code: "SS", name: "Sassari" },
  { code: "SV", name: "Savona" },
  { code: "SI", name: "Siena" },
  { code: "SR", name: "Siracusa" },
  { code: "SO", name: "Sondrio" },
  { code: "SU", name: "Sud Sardegna" },
  { code: "TA", name: "Taranto" },
  { code: "TE", name: "Teramo" },
  { code: "TR", name: "Terni" },
  { code: "TO", name: "Torino" },
  { code: "TP", name: "Trapani" },
  { code: "TN", name: "Trento" },
  { code: "TV", name: "Treviso" },
  { code: "TS", name: "Trieste" },
  { code: "UD", name: "Udine" },
  { code: "VA", name: "Varese" },
  { code: "VE", name: "Venezia" },
  { code: "VB", name: "Verbano-Cusio-Ossola" },
  { code: "VC", name: "Vercelli" },
  { code: "VR", name: "Verona" },
  { code: "VV", name: "Vibo Valentia" },
  { code: "VI", name: "Vicenza" },
  { code: "VT", name: "Viterbo" },
];

export const STATUS_LABELS: Record<string, string> = {
  draft: "Bozza",
  ready: "Pronto",
  published: "Pubblicato",
};

export const NARRATIVE_FIELDS = [
  { key: "target_acquirente", label: "Target acquirente", placeholder: "Es. famiglia in cerca di seconda casa, investitore..." },
  { key: "punti_di_forza", label: "Punti di forza", placeholder: "Es. vista mare, pietra a vista, posizione panoramica" },
  { key: "stile_descrizione", label: "Stile della descrizione", placeholder: "Es. raffinato, asciutto, narrativo" },
  { key: "livello_prestigio", label: "Livello di prestigio", placeholder: "Es. residenza esclusiva, casa di carattere" },
  { key: "elementi_storici", label: "Elementi storici/architettonici", placeholder: "Es. soffitti a volta, camino in pietra, affreschi" },
  { key: "vista_contesto", label: "Vista / contesto / atmosfera", placeholder: "Es. tramonti sulle Apuane, silenzio dei boschi" },
  { key: "lavori_recenti", label: "Lavori recenti", placeholder: "Es. tetto rifatto 2023, infissi nuovi" },
  { key: "ideale_per", label: "Ideale per", placeholder: "Es. smart-working, ritiro creativo, B&B di charme" },
  { key: "parole_da_enfatizzare", label: "Parole da enfatizzare", placeholder: "Es. autentico, luminoso, panoramico" },
  { key: "parole_da_evitare", label: "Parole da evitare", placeholder: "Es. occasione, affare, prezzo trattabile" },
] as const;

export type NarrativeKey = (typeof NARRATIVE_FIELDS)[number]["key"];

export const LENGTH_OPTIONS = [
  { value: "breve", label: "Breve", hint: "80–120 parole · per annuncio rapido" },
  { value: "media", label: "Media", hint: "180–250 parole · standard portali" },
  { value: "editoriale", label: "Editoriale / premium", hint: "350–500 parole · narrazione completa" },
] as const;

export const TONE_OPTIONS = [
  { value: "neutro", label: "Neutro professionale", hint: "Asciutto, informativo, autorevole" },
  { value: "emozionale", label: "Emozionale raffinato", hint: "Evocativo, sensoriale, letterario" },
  { value: "commerciale", label: "Commerciale premium", hint: "Persuasivo ma elegante, focus valore" },
] as const;